[package]
name = "image-resizer"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
image = "0.23.14"
wasm-bindgen = "0.2.74"

[dev-dependencies]
wasm-bindgen-test = "0.3.42"
